### PR TITLE
Tutorial fixes js sdk

### PR DESCRIPTION
**Pull request by icarusz**
Updating a few tutorial references for the change from tupelo.js -> tupelo-js-sdk

### CODE REVIEW

**Review by cap10morgan — COMMENTED** [review]
Are the `search-data.json` changes intended to be in here too?

**Review by aknuds1 — COMMENTED** [review]
Looks good to me, except also wondering about the search-data.json changes (not familiar with this file, so don't know why it might've changed).

**Comment by icarusz** [comment]
Yes, something in my Atom workflow with github is goofy.  These search changes are actually reverting to what it was BEFORE the 0.2.0 push.  Next time I will separate them out.

**Comment by aknuds1** [comment]
@icarusz Can we delete the branch?

**Pull request merged**
